import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSystemJobLogAndFileSize1786805424982 implements MigrationInterface {
    name = 'AddSystemJobLogAndFileSize1786805424982'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tests" DROP CONSTRAINT "tests_teacher_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "test_attempts" DROP CONSTRAINT "test_attempts_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "test_attempts" DROP CONSTRAINT "test_attempts_test_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "test_answers" DROP CONSTRAINT "test_answers_question_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "test_answers" DROP CONSTRAINT "test_answers_attempt_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" DROP CONSTRAINT "vip_upgrade_requests_reviewed_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" DROP CONSTRAINT "vip_upgrade_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP CONSTRAINT "test_questions_test_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" DROP CONSTRAINT "daily_practice_usage_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "user_vocabulary_progress_vocabulary_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "user_vocabulary_progress_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" DROP CONSTRAINT "speaking_attempts_graded_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" DROP CONSTRAINT "speaking_attempts_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "resources_uploader_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP CONSTRAINT "mistake_book_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" DROP CONSTRAINT "ai_generation_jobs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "practice_questions_lesson_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "practice_questions_level_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "practice_attempts_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "topics_recommended_level_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vocabularies" DROP CONSTRAINT "vocabularies_level_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" DROP CONSTRAINT "topic_vocabularies_vocabulary_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" DROP CONSTRAINT "topic_vocabularies_topic_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "lessons_level_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "lesson_contents_lesson_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "grammar_points" DROP CONSTRAINT "grammar_points_level_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "fk_assignment_assigned_to"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "fk_assignment_assigned_by"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "course_lessons_lesson_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "course_lessons_course_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."uq_tests_access_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tests_teacher_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_test_attempts_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_attempts_test_user_submitted"`);
        await queryRunner.query(`DROP INDEX "public"."uq_test_answers_attempt_question"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vip_upgrade_requests_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_test_questions_test_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_entitlement"`);
        await queryRunner.query(`DROP INDEX "public"."uq_daily_usage_user_key_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_progress_user_next_review"`);
        await queryRunner.query(`DROP INDEX "public"."idx_speaking_attempts_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resources_tier_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mistake_book_user_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mistake_book_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_requests_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_jobs_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_jobs_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_practice_questions_gen"`);
        await queryRunner.query(`DROP INDEX "public"."idx_practice_attempts_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_practice_attempts_user_type_created"`);
        await queryRunner.query(`DROP INDEX "public"."uq_topics_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_topics_status_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vocabularies_level_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vocabularies_hanzi"`);
        await queryRunner.query(`DROP INDEX "public"."uq_topic_vocabularies"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lessons_level_status_order"`);
        await queryRunner.query(`DROP INDEX "public"."uq_lesson_contents"`);
        await queryRunner.query(`DROP INDEX "public"."uq_hsk_levels_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_grammar_points_level_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_assigned_to"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_assigned_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_courses_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_courses_audience_status_order"`);
        await queryRunner.query(`DROP INDEX "public"."uq_course_lessons"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_activity"`);
        await queryRunner.query(`ALTER TABLE "tests" DROP CONSTRAINT "chk_tests_status"`);
        await queryRunner.query(`ALTER TABLE "test_attempts" DROP CONSTRAINT "chk_test_attempts_status"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" DROP CONSTRAINT "chk_vip_upgrade_requests_status"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP CONSTRAINT "chk_test_questions_type"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "chk_subscriptions_plan"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "chk_subscriptions_status"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "chk_mastery_level"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "chk_ef"`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" DROP CONSTRAINT "chk_speaking_attempts_status"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "chk_resources_tier"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "chk_resources_status"`);
        await queryRunner.query(`ALTER TABLE "contact_requests" DROP CONSTRAINT "chk_contact_requests_status"`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" DROP CONSTRAINT "chk_ai_jobs_type"`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" DROP CONSTRAINT "chk_ai_jobs_status"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "chk_practice_questions_type"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "chk_practice_questions_status"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "chk_practice_questions_answer_type"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "chk_practice_attempts_type"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "chk_practice_attempts_source"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "chk_practice_attempts_status"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "chk_topics_status"`);
        await queryRunner.query(`ALTER TABLE "vocabularies" DROP CONSTRAINT "chk_vocabularies_status"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "chk_lessons_status"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "chk_lesson_contents_type"`);
        await queryRunner.query(`ALTER TABLE "grammar_points" DROP CONSTRAINT "chk_grammar_points_status"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "chk_courses_audience"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "chk_courses_status"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "chk_users_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "chk_users_status"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "uq_user_vocab_progress"`);
        await queryRunner.query(`CREATE TABLE "system_job_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "job_name" character varying(100) NOT NULL, "status" character varying(20) NOT NULL, "error_message" text, "last_run" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_6ec4bd3e2a74b3bd9a9fdbd17f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "resources" ADD "file_size" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ALTER COLUMN "easiness_factor" SET DEFAULT '2.5'`);

        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_email_unique" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "UQ_1e4407fd8071b257b354643bd58" UNIQUE ("user_id", "vocabulary_id")`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" ADD CONSTRAINT "FK_cf57d54a28ce82317fa75903e0e" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabularies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD CONSTRAINT "FK_c68ce5afbd6b6b40fe077e7d729" FOREIGN KEY ("updatedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "system_configs" DROP CONSTRAINT "FK_c68ce5afbd6b6b40fe077e7d729"`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" DROP CONSTRAINT "FK_cf57d54a28ce82317fa75903e0e"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "UQ_1e4407fd8071b257b354643bd58"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email_unique"`);

        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ALTER COLUMN "easiness_factor" SET DEFAULT 2.50`);
        await queryRunner.query(`ALTER TABLE "resources" DROP COLUMN "file_size"`);
        await queryRunner.query(`DROP TABLE "system_job_logs"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "uq_user_vocab_progress" UNIQUE ("user_id", "vocabulary_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "chk_users_status" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'BANNED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "chk_users_role" CHECK (((role)::text = ANY ((ARRAY['FREE'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "chk_courses_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "chk_courses_audience" CHECK (((audience)::text = ANY ((ARRAY['ADULT'::character varying, 'CHILD'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "grammar_points" ADD CONSTRAINT "chk_grammar_points_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "chk_lesson_contents_type" CHECK (((content_type)::text = ANY ((ARRAY['VOCABULARY'::character varying, 'GRAMMAR'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "chk_lessons_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "vocabularies" ADD CONSTRAINT "chk_vocabularies_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "chk_topics_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "chk_practice_attempts_status" CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "chk_practice_attempts_source" CHECK (((source_type)::text = ANY ((ARRAY['LEVEL'::character varying, 'LESSON'::character varying, 'TOPIC'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "chk_practice_attempts_type" CHECK (((practice_type)::text = ANY ((ARRAY['WORD_MATCHING'::character varying, 'FLASHCARD'::character varying, 'FILL_BLANK'::character varying, 'SENTENCE_ORDERING'::character varying, 'PINYIN_BALLOON_GAME'::character varying, 'MEMORY_GAME'::character varying, 'HANZI_WRITING'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "chk_practice_questions_answer_type" CHECK (((answer_type IS NULL) OR ((answer_type)::text = ANY ((ARRAY['HANZI'::character varying, 'PINYIN'::character varying, 'TEXT'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "chk_practice_questions_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "chk_practice_questions_type" CHECK (((question_type)::text = ANY ((ARRAY['FILL_BLANK'::character varying, 'SENTENCE_ORDERING'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" ADD CONSTRAINT "chk_ai_jobs_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" ADD CONSTRAINT "chk_ai_jobs_type" CHECK (((job_type)::text = ANY ((ARRAY['STORY'::character varying, 'STUDY_PATH'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "contact_requests" ADD CONSTRAINT "chk_contact_requests_status" CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'CONTACTED'::character varying, 'CLOSED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "chk_resources_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "chk_resources_tier" CHECK (((tier)::text = ANY ((ARRAY['FREE'::character varying, 'VIP'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ADD CONSTRAINT "chk_speaking_attempts_status" CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'GRADED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "chk_ef" CHECK (((easiness_factor >= 1.3) AND (easiness_factor <= 2.6)))`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "chk_mastery_level" CHECK (((mastery_level >= 0) AND (mastery_level <= 4)))`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "chk_subscriptions_status" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "chk_subscriptions_plan" CHECK (((plan)::text = ANY ((ARRAY['FREE'::character varying, 'VIP'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD CONSTRAINT "chk_test_questions_type" CHECK (((question_type)::text = ANY ((ARRAY['SINGLE_CHOICE'::character varying, 'TRUE_FALSE'::character varying, 'SHORT_ANSWER'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ADD CONSTRAINT "chk_vip_upgrade_requests_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "test_attempts" ADD CONSTRAINT "chk_test_attempts_status" CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'SUBMITTED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "tests" ADD CONSTRAINT "chk_tests_status" CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'CLOSED'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_users_activity" ON "users" ("last_activity_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_course_lessons" ON "course_lessons" ("course_id", "lesson_id") `);
        await queryRunner.query(`CREATE INDEX "idx_courses_audience_status_order" ON "courses" ("audience", "status", "display_order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_courses_slug" ON "courses" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_status" ON "assignments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_assigned_by" ON "assignments" ("assigned_by") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_assigned_to" ON "assignments" ("assigned_to") `);
        await queryRunner.query(`CREATE INDEX "idx_grammar_points_level_status" ON "grammar_points" ("level_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_hsk_levels_code" ON "hsk_levels" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_lesson_contents" ON "lesson_contents" ("lesson_id", "content_type", "content_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lessons_level_status_order" ON "lessons" ("level_id", "display_order", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_topic_vocabularies" ON "topic_vocabularies" ("topic_id", "vocabulary_id") `);
        await queryRunner.query(`CREATE INDEX "idx_vocabularies_hanzi" ON "vocabularies" ("hanzi") `);
        await queryRunner.query(`CREATE INDEX "idx_vocabularies_level_status" ON "vocabularies" ("level_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_topics_status_order" ON "topics" ("status", "display_order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_topics_slug" ON "topics" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_practice_attempts_user_type_created" ON "practice_attempts" ("user_id", "practice_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_practice_attempts_user_status" ON "practice_attempts" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_practice_questions_gen" ON "practice_questions" ("question_type", "level_id", "status") WHERE ((status)::text = 'PUBLISHED'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_ai_jobs_user_status" ON "ai_generation_jobs" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_jobs_status_created" ON "ai_generation_jobs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_contact_requests_status_created" ON "contact_requests" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_mistake_book_user_created" ON "mistake_book" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_mistake_book_user_source" ON "mistake_book" ("user_id", "source_type", "source_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_resources_tier_status_created" ON "resources" ("tier", "status", "created_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_speaking_attempts_user_status" ON "speaking_attempts" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_progress_user_next_review" ON "user_vocabulary_progress" ("user_id", "next_review_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_daily_usage_user_key_date" ON "daily_practice_usage" ("user_id", "activity_key", "usage_date") `);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_entitlement" ON "subscriptions" ("user_id", "plan", "status", "expires_at") WHERE ((status)::text = 'ACTIVE'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_test_questions_test_order" ON "test_questions" ("test_id", "display_order") `);
        await queryRunner.query(`CREATE INDEX "idx_vip_upgrade_requests_user_status" ON "vip_upgrade_requests" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_test_answers_attempt_question" ON "test_answers" ("attempt_id", "question_id") `);
        await queryRunner.query(`CREATE INDEX "idx_test_attempts_test_user_submitted" ON "test_attempts" ("test_id", "user_id", "submitted_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_test_attempts_active" ON "test_attempts" ("test_id", "user_id") WHERE ((status)::text = 'IN_PROGRESS'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_tests_teacher_status" ON "tests" ("teacher_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_tests_access_code" ON "tests" ("access_code") WHERE (access_code IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "course_lessons_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "course_lessons_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignment_assigned_by" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignment_assigned_to" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grammar_points" ADD CONSTRAINT "grammar_points_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "lesson_contents_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "lessons_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" ADD CONSTRAINT "topic_vocabularies_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" ADD CONSTRAINT "topic_vocabularies_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabularies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabularies" ADD CONSTRAINT "vocabularies_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "topics_recommended_level_id_fkey" FOREIGN KEY ("recommended_level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "practice_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "practice_questions_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "practice_questions_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" ADD CONSTRAINT "ai_generation_jobs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD CONSTRAINT "mistake_book_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "resources_uploader_id_fkey" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ADD CONSTRAINT "speaking_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ADD CONSTRAINT "speaking_attempts_graded_by_fkey" FOREIGN KEY ("graded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "user_vocabulary_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "user_vocabulary_progress_vocabulary_id_fkey" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabularies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" ADD CONSTRAINT "daily_practice_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD CONSTRAINT "test_questions_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ADD CONSTRAINT "vip_upgrade_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ADD CONSTRAINT "vip_upgrade_requests_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_answers" ADD CONSTRAINT "test_answers_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "test_attempts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_answers" ADD CONSTRAINT "test_answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "test_questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_attempts" ADD CONSTRAINT "test_attempts_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_attempts" ADD CONSTRAINT "test_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tests" ADD CONSTRAINT "tests_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
