import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTotalExpToUser1787303506253 implements MigrationInterface {
    name = 'AddTotalExpToUser1787303506253'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "UQ_1e4407fd8071b257b354643bd58"`);
        await queryRunner.query(`CREATE TABLE "user_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "reward_id" uuid NOT NULL, "idempotency_key" character varying(64), "type" character varying(30) NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "is_used" boolean NOT NULL DEFAULT false, "redeemed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_86078010f64a891601beef7c54f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_rewards_user_used" ON "user_rewards" ("user_id", "is_used") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_rewards_idem" ON "user_rewards" ("user_id", "idempotency_key") WHERE idempotency_key IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "user_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "activity_type" character varying(30) NOT NULL, "details" jsonb, "exp_awarded" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_1245d4d2cf04ba7743f2924d951" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_activities_user_created" ON "user_activities" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_user_activities_user" ON "user_activities" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "title" character varying(120) NOT NULL, "type" character varying(30) NOT NULL, "cost_exp" integer NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_rewards_code" ON "rewards" ("code") `);
        await queryRunner.query(`CREATE TABLE "exp_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "amount" integer NOT NULL, "type" character varying(30) NOT NULL, "ref_type" character varying(30), "ref_id" uuid, "idempotency_key" character varying(64), CONSTRAINT "PK_d30ed50b64ae9784da1c3cf94dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_exp_tx_user_created" ON "exp_transactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "exp_daily_earnings" ("user_id" uuid NOT NULL, "date" date NOT NULL, "earned" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_d56ade5562002adf8588d2fcb4d" PRIMARY KEY ("user_id", "date"))`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP COLUMN "options"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP COLUMN "correct_answer"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP COLUMN "question_type"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "total_exp" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "current_exp" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "question_type" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "source_type" character varying(20) NOT NULL DEFAULT 'EXAM'`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "topic_id" uuid`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "hidden_by_admin" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "hide_reason" text`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "hidden_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD "question_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_assignments" ADD "status_on_submit" character varying(20) NOT NULL DEFAULT 'GRADED'`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "scope" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "question_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "vocabulary_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "fail_count" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "correct_streak" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "last_failed_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD "last_reviewed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD "topic_id" uuid`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "type" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ALTER COLUMN "amount" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "hsk_levels" ADD CONSTRAINT "UQ_c9f72266eac80d754f29657b3f5" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ALTER COLUMN "easiness_factor" SET DEFAULT '2.5'`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ALTER COLUMN "score" TYPE numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "practice_attempts_pkey"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "practice_attempts_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "valueType"`);
        await queryRunner.query(`DROP TYPE "public"."system_configs_valuetype_enum"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "valueType" character varying(20) NOT NULL DEFAULT 'STRING'`);
        await queryRunner.query(`CREATE INDEX "idx_uvp_user_next_review" ON "user_vocabulary_progress" ("user_id", "next_review_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_uvp_user_vocab" ON "user_vocabulary_progress" ("user_id", "vocabulary_id") `);
        await queryRunner.query(`CREATE INDEX "idx_resources_tier_status" ON "resources" ("tier", "status", "created_at") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_mistake_book_user_source" ON "mistake_book" ("user_id", "source_type", "source_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_mistake_book_user_created" ON "mistake_book" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_jobs_status_created" ON "ai_generation_jobs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_practice_attempts_user_type_created" ON "practice_attempts" ("user_id", "practice_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_practice_attempts_user_status" ON "practice_attempts" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_practice_attempts_idem" ON "practice_attempts" ("user_id", "idempotency_key") WHERE idempotency_key IS NOT NULL`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" ADD CONSTRAINT "UQ_7dc2ee681da0c794fb703a4d5a4" UNIQUE ("user_id", "activity_key", "usage_date")`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" ADD CONSTRAINT "UQ_730d6e2e304139dfdcc85ecbf0b" UNIQUE ("topic_id", "vocabulary_id")`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "UQ_98887a6fb8a40ef6880dc9433e1" UNIQUE ("lesson_id", "content_type", "content_id")`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "UQ_0519f7350731756a9a4666a037c" UNIQUE ("course_id", "lesson_id")`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD CONSTRAINT "FK_5badfac5ec550e555213ad2e5bc" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD CONSTRAINT "FK_275f99133c07faa04deeda6e489" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_attempts" ADD CONSTRAINT "FK_88b08b09eb90ae8d6afb2147b5e" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_attempts" ADD CONSTRAINT "FK_193bbf9a4f34822e0aa41fefc92" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_answers" ADD CONSTRAINT "FK_af38abdfbe0920762f26b8a506e" FOREIGN KEY ("attempt_id") REFERENCES "test_attempts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_answers" ADD CONSTRAINT "FK_f6de6b25f1837cee4f7e1213ec3" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ADD CONSTRAINT "FK_47132c418fdbfb54759da8f9aff" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ADD CONSTRAINT "FK_9ff1f0d068ecd366ef5d9245ae7" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" ADD CONSTRAINT "FK_998540156ef18852f92988c1610" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "FK_78240992f63218b86eb49e7c2e5" FOREIGN KEY ("recommended_level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" ADD CONSTRAINT "FK_490493f27735f8749a596d9ed86" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabularies" ADD CONSTRAINT "FK_6ba37e90cb27887d8d654b4e5a2" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_7cceeefa847caf410e3c79a66af" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "FK_96188b677e634541bf8545cac9e" FOREIGN KEY ("vocabulary_id") REFERENCES "vocabularies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ADD CONSTRAINT "FK_b69556883458c62d7e290598bb4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ADD CONSTRAINT "FK_e345aeb8144885a01e19ab5b51b" FOREIGN KEY ("graded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "FK_bf650039fa84491f02d72691ea2" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mistake_book" ADD CONSTRAINT "FK_79452e379d66b323b225a23e7a3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" ADD CONSTRAINT "FK_fda8358a42ab640f3479ddcc246" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_bef74ccec84ea34dde9ae8b8629" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "FK_a54868295e9ba8337cb7f975064" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "FK_824afebd218ea53227f8383b521" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_questions" ADD CONSTRAINT "FK_550435d673604aab78aa087ba47" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "FK_49dc54e892aea5903b7d8256b51" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "FK_118fa95e3bfeb4fc10406f72cf1" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "FK_1bb754da7dd104c4a3beb9677c8" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "FK_90b56bba59a6dc2d10675e05233" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grammar_points" ADD CONSTRAINT "FK_574ab623cb7b95d3bc0231a3920" FOREIGN KEY ("level_id") REFERENCES "hsk_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "grammar_points" DROP CONSTRAINT "FK_574ab623cb7b95d3bc0231a3920"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "FK_90b56bba59a6dc2d10675e05233"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "FK_1bb754da7dd104c4a3beb9677c8"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "FK_118fa95e3bfeb4fc10406f72cf1"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "FK_49dc54e892aea5903b7d8256b51"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "FK_550435d673604aab78aa087ba47"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "FK_824afebd218ea53227f8383b521"`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP CONSTRAINT "FK_a54868295e9ba8337cb7f975064"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_bef74ccec84ea34dde9ae8b8629"`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" DROP CONSTRAINT "FK_fda8358a42ab640f3479ddcc246"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP CONSTRAINT "FK_79452e379d66b323b225a23e7a3"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "FK_bf650039fa84491f02d72691ea2"`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" DROP CONSTRAINT "FK_e345aeb8144885a01e19ab5b51b"`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" DROP CONSTRAINT "FK_b69556883458c62d7e290598bb4"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_96188b677e634541bf8545cac9e"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" DROP CONSTRAINT "FK_7cceeefa847caf410e3c79a66af"`);
        await queryRunner.query(`ALTER TABLE "vocabularies" DROP CONSTRAINT "FK_6ba37e90cb27887d8d654b4e5a2"`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" DROP CONSTRAINT "FK_490493f27735f8749a596d9ed86"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_78240992f63218b86eb49e7c2e5"`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" DROP CONSTRAINT "FK_998540156ef18852f92988c1610"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" DROP CONSTRAINT "FK_9ff1f0d068ecd366ef5d9245ae7"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" DROP CONSTRAINT "FK_47132c418fdbfb54759da8f9aff"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "test_answers" DROP CONSTRAINT "FK_f6de6b25f1837cee4f7e1213ec3"`);
        await queryRunner.query(`ALTER TABLE "test_answers" DROP CONSTRAINT "FK_af38abdfbe0920762f26b8a506e"`);
        await queryRunner.query(`ALTER TABLE "test_attempts" DROP CONSTRAINT "FK_193bbf9a4f34822e0aa41fefc92"`);
        await queryRunner.query(`ALTER TABLE "test_attempts" DROP CONSTRAINT "FK_88b08b09eb90ae8d6afb2147b5e"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP CONSTRAINT "FK_275f99133c07faa04deeda6e489"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP CONSTRAINT "FK_5badfac5ec550e555213ad2e5bc"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "UQ_0519f7350731756a9a4666a037c"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "UQ_98887a6fb8a40ef6880dc9433e1"`);
        await queryRunner.query(`ALTER TABLE "topic_vocabularies" DROP CONSTRAINT "UQ_730d6e2e304139dfdcc85ecbf0b"`);
        await queryRunner.query(`ALTER TABLE "daily_practice_usage" DROP CONSTRAINT "UQ_7dc2ee681da0c794fb703a4d5a4"`);
        await queryRunner.query(`DROP INDEX "public"."uq_practice_attempts_idem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_practice_attempts_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_practice_attempts_user_type_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_jobs_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mistake_book_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mistake_book_user_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resources_tier_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_uvp_user_vocab"`);
        await queryRunner.query(`DROP INDEX "public"."idx_uvp_user_next_review"`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "valueType"`);
        await queryRunner.query(`CREATE TYPE "public"."system_configs_valuetype_enum" AS ENUM('INT', 'STRING', 'BOOLEAN', 'JSON')`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "valueType" "public"."system_configs_valuetype_enum" NOT NULL DEFAULT 'STRING'`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" DROP CONSTRAINT "practice_attempts_pkey"`);
        await queryRunner.query(`ALTER TABLE "practice_attempts" ADD CONSTRAINT "practice_attempts_pkey" PRIMARY KEY ("id", "created_at")`);
        await queryRunner.query(`ALTER TABLE "speaking_attempts" ALTER COLUMN "score" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ALTER COLUMN "easiness_factor" SET DEFAULT 2.5`);
        await queryRunner.query(`ALTER TABLE "hsk_levels" DROP CONSTRAINT "UQ_c9f72266eac80d754f29657b3f5"`);
        await queryRunner.query(`ALTER TABLE "vip_upgrade_requests" ALTER COLUMN "amount" TYPE numeric(10,0)`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practice_questions" DROP COLUMN "topic_id"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "last_reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "last_failed_at"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "correct_streak"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "fail_count"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "vocabulary_id"`);
        await queryRunner.query(`ALTER TABLE "mistake_book" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "test_assignments" DROP COLUMN "status_on_submit"`);
        await queryRunner.query(`ALTER TABLE "test_questions" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "hidden_at"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "hide_reason"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "hidden_by_admin"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "topic_id"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "source_type"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "question_type"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "current_exp"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "total_exp"`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD "question_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD "correct_answer" jsonb`);
        await queryRunner.query(`ALTER TABLE "test_questions" ADD "options" jsonb`);
        await queryRunner.query(`DROP TABLE "exp_daily_earnings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_exp_tx_user_created"`);
        await queryRunner.query(`DROP TABLE "exp_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."uq_rewards_code"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_activities_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_activities_user_created"`);
        await queryRunner.query(`DROP TABLE "user_activities"`);
        await queryRunner.query(`DROP INDEX "public"."uq_user_rewards_idem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_rewards_user_used"`);
        await queryRunner.query(`DROP TABLE "user_rewards"`);
        await queryRunner.query(`ALTER TABLE "user_vocabulary_progress" ADD CONSTRAINT "UQ_1e4407fd8071b257b354643bd58" UNIQUE ("user_id", "vocabulary_id")`);
    }

}
